---
title: "Get to Know the MAUP"
author: "Marc Weber"
format: revealjs
editor: visual
---

## What is the Modifiable Areal Unit Problem (MAUP)

- When data are gathered according to different boundary definitions, different data sets are generated
- Analyzing these different data sets will likely provide different results
- When point-based measures of spatial phenomena are aggregated into districts (i.e. population density or illness rates) resulting summary values (e.g., totals, rates, proportions, densities) are influenced by both the shape and scale of the aggregation unit.


## Zoning Effect and Scale Effect

- Zoning effect: number of areal units kept constant but new boundaries drawn to create new configurations or 'zones'
- Scale effect: Spatial (dis) aggregation - changing the spatial resolution of the data


## A worked example


```{r}
library(tigris)
library(tidycensus)
library(tmap)
library(mapview)
library(ggplot2)
mapviewOptions(fgb=FALSE)

pdx <- get_acs(
  state = "OR",
  county = "Multnomah",
  geography = "cbg",
  variables = "B19013_001",
  geometry = TRUE,
  year = 2020
)

head(pdx)

pdx %>%
  ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  scale_fill_viridis_c(option = "magma") 

```

